export default {
  START_GAME: 'START_GAME',
  END_GAME: 'END_GAME',
  START_EDIT: 'START_EDIT',
  SAVE_EDIT: 'SAVE_EDIT',
  START_SAVE: 'START_SAVE',
  DISCARD_EDIT: 'DISCARD_EDIT',
  SELECT_BOARD: 'SELECT_BOARD',
  CREATE_BOARD: 'CREATE_BOARD',
};
